# Generated by Django 3.2.4 on 2022-03-02 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('cab', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('site', models.CharField(default='Parapharma', max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=10000)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('created', models.CharField(default=datetime.date(2022, 3, 2), max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amana.status')),
            ],
        ),
    ]
       

