# Generated by Django 3.2.4 on 2022-06-17 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='created',
            field=models.CharField(default=datetime.date(2022, 6, 17), max_length=100),
        ),
    ]
